include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*3.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
