name: chia_client
description: RPC client for the Chia blockchain
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  petitparser: ^5.0.0
  petitparser_examples: ^5.0.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0
